### ISSUE TITLE
Sidebar Navigation is not translated

### ISSUE THREAD

**Issue by ibdz** [ItsJonQ/wordpress-design-guidelines#10]
![色 WordPress Design Guidelines](https://user-images.githubusercontent.com/426383/68029078-c98c9280-fcf9-11e9-90d1-7ffa30377df3.png)

The translation for sidebar is missing. The links for each page also incorrect (link to original English content).

**Comment by ItsJonQ** [comment]
@ibdz Thanks for the heads up! I just resolved this with the latest push :)

https://wp-design-guidelines.netlify.com/ja/foundations/

<img width="1101" alt="Screen Shot 2019-11-01 at 10 24 33 AM" src="https://user-images.githubusercontent.com/2322354/68035697-22c0db80-fc92-11e9-83ba-2d6a5ad7c801.png">

I'll need to come up with a nicer way of handling links and translations.
They currently exist in a `.js` file. Which works... but it could be nicer :)
