### ISSUE TITLE
Suggest color hue to maintain good contrast

### ISSUE THREAD

**Issue by enriquesanchez** [ItsJonQ/wordpress-design-guidelines#4]
I _love_ that when selecting a color, the contrast score is included in the card:

<img width="308" alt="Screen Shot 2019-10-09 at 1 10 06 PM" src="https://user-images.githubusercontent.com/3276087/66508421-b558cb00-ea96-11e9-98e3-c765d186ab37.png">

I noticed that it also suggests to use "dark text" to maintain said contrast. 

I wonder if it's possible to actually suggest a color hue to achieve AA compliance. So, instead of "dark text", we could say "For text, use Dark Gray 400 or darker".

Does that make sense?

**Comment by ItsJonQ** [comment]
@enriquesanchez Ooo! Interesting.

For some context, @melchoyce suggested that the contrast scoring (for dark text) should be against `Dark Gray 900` (`#191e23`). Previously I had black (`#000`).

I'm not sure if that changes anything, haha

I'm not an accessibility contrast expert. I'd love to know some examples of how certain colours may be better for certain situations. Once I understand, I can build that into the logic :)

**Comment by enriquesanchez** [comment]
>For some context, @melchoyce suggested that the contrast scoring (for dark text) should be against Dark Gray 900 (#191e23)

Oh, this is great then. I think it would be more clear if we specified that, instead of just saying "dark".

So, something like "Use `Dark Gray 900` text with this color". Maybe that copy can be more clear, but you get my point :)

**Comment by ItsJonQ** [comment]
@enriquesanchez Gotcha! can do!!
